<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Nationality extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            ['name' => 'Afganistán', 'code' => 'AF', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Albania', 'code' => 'AL', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Alemania', 'code' => 'DE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Andorra', 'code' => 'AD', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angola', 'code' => 'AO', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Antigua y Barbuda', 'code' => 'AG', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Arabia Saudita', 'code' => 'SA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Argelia', 'code' => 'DZ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Argentina', 'code' => 'AR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Armenia', 'code' => 'AM', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Australia', 'code' => 'AU', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Austria', 'code' => 'AT', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Azerbaiyán', 'code' => 'AZ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bahamas', 'code' => 'BS', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladés', 'code' => 'BD', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Barbados', 'code' => 'BB', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Baréin', 'code' => 'BH', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bélgica', 'code' => 'BE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Belice', 'code' => 'BZ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Benín', 'code' => 'BJ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bielorrusia', 'code' => 'BY', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bolivia', 'code' => 'BO', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bosnia y Herzegovina', 'code' => 'BA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Botsuana', 'code' => 'BW', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brasil', 'code' => 'BR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brunéi', 'code' => 'BN', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bulgaria', 'code' => 'BG', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Burundi', 'code' => 'BI', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bután', 'code' => 'BT', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cabo Verde', 'code' => 'CV', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Camboya', 'code' => 'KH', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Camerún', 'code' => 'CM', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Canadá', 'code' => 'CA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Catar', 'code' => 'QA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chad', 'code' => 'TD', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chile', 'code' => 'CL', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'China', 'code' => 'CN', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chipre', 'code' => 'CY', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ciudad del Vaticano', 'code' => 'VA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Colombia', 'code' => 'CO', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Comoras', 'code' => 'KM', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Congo (Brazzaville)', 'code' => 'CG', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Congo (Kinshasa)', 'code' => 'CD', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Corea del Norte', 'code' => 'KP', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Corea del Sur', 'code' => 'KR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Costa de Marfil', 'code' => 'CI', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Costa Rica', 'code' => 'CR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Croacia', 'code' => 'HR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cuba', 'code' => 'CU', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dinamarca', 'code' => 'DK', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dominica', 'code' => 'DM', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ecuador', 'code' => 'EC', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Egipto', 'code' => 'EG', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'El Salvador', 'code' => 'SV', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Emiratos Árabes Unidos', 'code' => 'AE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eritrea', 'code' => 'ER', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eslovaquia', 'code' => 'SK', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eslovenia', 'code' => 'SI', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'España', 'code' => 'ES', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Estados Unidos', 'code' => 'US', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Estonia', 'code' => 'EE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Esuatini', 'code' => 'SZ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Etiopía', 'code' => 'ET', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Filipinas', 'code' => 'PH', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Finlandia', 'code' => 'FI', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fiyi', 'code' => 'FJ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Francia', 'code' => 'FR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gabón', 'code' => 'GA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gambia', 'code' => 'GM', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Georgia', 'code' => 'GE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ghana', 'code' => 'GH', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Granada', 'code' => 'GD', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Grecia', 'code' => 'GR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guatemala', 'code' => 'GT', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guinea', 'code' => 'GN', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guinea-Bisáu', 'code' => 'GW', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guinea Ecuatorial', 'code' => 'GQ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guyana', 'code' => 'GY', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Haití', 'code' => 'HT', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Honduras', 'code' => 'HN', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hungría', 'code' => 'HU', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'India', 'code' => 'IN', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Indonesia', 'code' => 'ID', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Irak', 'code' => 'IQ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Irán', 'code' => 'IR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Irlanda', 'code' => 'IE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Islandia', 'code' => 'IS', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Islas Marshall', 'code' => 'MH', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Islas Salomón', 'code' => 'SB', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Israel', 'code' => 'IL', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Italia', 'code' => 'IT', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jamaica', 'code' => 'JM', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Japón', 'code' => 'JP', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jordania', 'code' => 'JO', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kazajistán', 'code' => 'KZ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kenia', 'code' => 'KE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kirguistán', 'code' => 'KG', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiribati', 'code' => 'KI', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kuwait', 'code' => 'KW', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Laos', 'code' => 'LA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lesoto', 'code' => 'LS', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Letonia', 'code' => 'LV', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Líbano', 'code' => 'LB', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Liberia', 'code' => 'LR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Libia', 'code' => 'LY', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lituania', 'code' => 'LT', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Luxemburgo', 'code' => 'LU', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Macedonia del Norte', 'code' => 'MK', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Madagascar', 'code' => 'MG', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Malasia', 'code' => 'MY', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Malaui', 'code' => 'MW', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Maldivas', 'code' => 'MV', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Malí', 'code' => 'ML', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Malta', 'code' => 'MT', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Marruecos', 'code' => 'MA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mauricio', 'code' => 'MU', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mauritania', 'code' => 'MR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'México', 'code' => 'MX', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Micronesia', 'code' => 'FM', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Moldavia', 'code' => 'MD', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mónaco', 'code' => 'MC', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mongolia', 'code' => 'MN', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Montenegro', 'code' => 'ME', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mozambique', 'code' => 'MZ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Namibia', 'code' => 'NA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nauru', 'code' => 'NR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nepal', 'code' => 'NP', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nicaragua', 'code' => 'NI', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Níger', 'code' => 'NE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nigeria', 'code' => 'NG', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Noruega', 'code' => 'NO', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nueva Zelanda', 'code' => 'NZ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Omán', 'code' => 'OM', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Países Bajos', 'code' => 'NL', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pakistán', 'code' => 'PK', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Palaos', 'code' => 'PW', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Palestina', 'code' => 'PS', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Panamá', 'code' => 'PA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Papúa Nueva Guinea', 'code' => 'PG', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Paraguay', 'code' => 'PY', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Perú', 'code' => 'PE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Polonia', 'code' => 'PL', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Portugal', 'code' => 'PT', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Reino Unido', 'code' => 'GB', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'República Centroafricana', 'code' => 'CF', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'República Checa', 'code' => 'CZ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'República Dominicana', 'code' => 'DO', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ruanda', 'code' => 'RW', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rumania', 'code' => 'RO', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rusia', 'code' => 'RU', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Samoa', 'code' => 'WS', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'San Cristóbal y Nieves', 'code' => 'KN', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'San Marino', 'code' => 'SM', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'San Vicente y las Granadinas', 'code' => 'VC', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Santa Lucía', 'code' => 'LC', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Santo Tomé y Príncipe', 'code' => 'ST', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Senegal', 'code' => 'SN', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Serbia', 'code' => 'RS', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Seychelles', 'code' => 'SC', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sierra Leona', 'code' => 'SL', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Singapur', 'code' => 'SG', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Siria', 'code' => 'SY', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Somalia', 'code' => 'SO', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sudáfrica', 'code' => 'ZA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sudán', 'code' => 'SD', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sudán del Sur', 'code' => 'SS', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Suecia', 'code' => 'SE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Suiza', 'code' => 'CH', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Surinam', 'code' => 'SR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tailandia', 'code' => 'TH', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Taiwán', 'code' => 'TW', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tanzania', 'code' => 'TZ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tayikistán', 'code' => 'TJ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Timor Oriental', 'code' => 'TL', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Togo', 'code' => 'TG', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tonga', 'code' => 'TO', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trinidad y Tobago', 'code' => 'TT', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Túnez', 'code' => 'TN', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turkmenistán', 'code' => 'TM', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turquía', 'code' => 'TR', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tuvalu', 'code' => 'TV', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ucrania', 'code' => 'UA', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uganda', 'code' => 'UG', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uruguay', 'code' => 'UY', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uzbekistán', 'code' => 'UZ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vanuatu', 'code' => 'VU', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Venezuela', 'code' => 'VE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vietnam', 'code' => 'VN', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yemen', 'code' => 'YE', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yibuti', 'code' => 'DJ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zambia', 'code' => 'ZM', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zimbabue', 'code' => 'ZW', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Birmania', 'code' => 'MM', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
